---
# tasks file for logstash_role

# Add repository 

- block: #============Block for Debian OS=====================
# Upgrade OS
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=2

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
#--------------------------------------------------------------
# Add repository 
  - name: Add an Apt signing key, uses whichever key is at the URL 
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  
  - name: Add repository in list of repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main 
      state: present

  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=2

# INSTALL LOGSTASH
  - name: Install Logstash service
    apt: name=logstash update_cache=yes state=latest
    
  - name: Check Logstash-path 
    shell: cd /etc/logstash/conf.d && pwd
    register: logstash_path

  - debug:
      var: logstash_path.stdout

# EDIT CONFIG LOGSTASH
  - name: Add user into folder /etc/sudoers.d/mike-adde 
    lineinfile:
      path: /etc/sudoers.d/mike-added
      line: 'logstash ALL=(ALL) NOPASSWD:ALL'

  - name: Add user "logstash" in group adm, sudo
    ansible.builtin.user:
      name: "{{ item }}"
      groups: sudo,adm
      append: yes
    with_items:
      - mikuser
      - logstash

  - name: CHOWN /usr/share/logstash
    ansible.builtin.file:
      path: /usr/share/logstash/
      state: directory
      owner: logstash
      group: logstash
      recurse: yes

  - name: CHMOD 0777 /usr/share/logstash/data
    ansible.builtin.file:
      path: /etc/share/logstash/data
      state: directory
      mode: '0777'

  - name: COPY config.file.conf of logstash
    copy: src=mik.conf dest={{ destipath_logstash_conf }} mode=0555
  
  - name: Check logstash config response
    shell: sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash -t
    register: logstash_config_answer

  - debug:
      var: logstash_config_answer.stdout

  - name: Start Logstash and Enable it on the every boot
    service: name=logstash state=started enabled=yes

# Secondary CHOWN  of log folder
  - name: CHOWN /usr/share/logstash
    ansible.builtin.file:
      path: /usr/share/logstash
      state: directory
      owner: logstash
      group: logstash
      recurse: yes

#Check file-path of logstash
  - name: Check path /usr/share/logstash/mikelog
    shell: ls -l /usr/share/logstash/
    register: logstash_folder

  - debug:
      var: logstash_folder.stdout_lines

  - name: Restart LOGSTASH
    service: name=logstash state=restarted


# INSTALL ELASTICSEARCH
  - name: Install Elasticsearch service
    apt: name=elasticsearch update_cache=yes state=latest

#Check file-path
  - name: Check Elasticsearch-path 
    shell: cd /etc/elasticsearch && ls -l
    register: elasticsearch_folder

  - debug:
      var: elasticsearch_folder.stdout_lines
      
# EDIT CONFIG  ELASTICSEARCH      
  - name: Edit CONFIG NETWORK.HOST in /etc/elasticsearch/elasticsearch.yml
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#network.host: 192.168.0.1'
      line: 'network.host: localhost'

  - name: Edit CONFIG CLUSTER.NAME in /etc/elasticsearch/elasticsearch.yml
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#cluster.name: '
      line: 'cluster.name: logstash-cluster'   

# CAT CONFIG  ELASTICSEARCH : /etc/elasticsearch/elasticsearch.yml    
#  - name: Cat /etc/elasticsearch/elasticsearch.yml
#    shell: cat /etc/elasticsearch/elasticsearch.yml  
#    register: elasticsearch_config
#
#  - debug:
#      var: elasticsearch_config.stdout_lines
    
  - name: Start ELASTICSEARCH and Enable it on the every boot
    service: name=elasticsearch state=started enabled=yes
      
# Check  state ELASTICSEARCH    
  - name: Checking  state ELASTICSEARCH 
    shell: service elasticsearch status  
    register: elasticsearch_state

  - debug:
      var: elasticsearch_state.stdout_lines
    
# Check_page in browser
  - name: Check result a page returns from Elasticsearch
    uri:
      url: http://localhost:9200/
      method: GET
      return_content: yes
    register: elastic_page
  
  - debug:
      var: elastic_page.json
      
# Add repository 
#  - name: Add repository key into apt-utility
#    command: curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

#  - name: Add repository-elastic into list of repo
#    command: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

#  - name: Update apt repo and cache
#    apt: update_cache=yes force_apt_get=yes cache_valid_time=2

#  - name: Install Logstash service
#    apt: name=logstash update_cache=yes state=latest

  when: ansible_system == "Linux"
