---
# tasks file for kibana_role

# Add repository 

- block: #============Block for Debian OS=====================
# Upgrade OS
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=2

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
#--------------------------------------------------------------

# Add repository 
  - name: Add an Apt signing key, uses whichever key is at the URL 
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  
  - name: Add repository in list of repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main 
      state: present

  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=2

# INSTALL KIBANA
  - name: Install KIBANA service
    apt: name=kibana update_cache=yes state=latest

  - name: Start KIBANA and Enable it on the every boot
    service: name=kibana state=started enabled=yes

  - name: Setup CONFIGS-file for NGINX work like proxy Servers
    copy: src=main_domain dest={{ destipath_nginx_server_conf }} mode=0555

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  /etc/nginx/sites-available/main_domain
      dest: /etc/nginx/sites-enabled/main_domain
      state: link

# RSYSLOG DISABLE UFW
  - name: Disable the ufw firewall (on Ubuntu, if configured).
    service:
      name: ufw
      state: stopped
      enabled: false
# RSYSLOG remote client config
  - name: RSYSLOG Setup client CONFIGS-file 
    copy: src=rsys.conf dest={{ destipath_rsyslog_conf }} mode=0555

# RSYSLOG RESTART
  - name: Restart RSYSLOG
    service: name=rsyslog state=restarted


# MONIT RESTART
  - name: Restart MONIT
    service: name=monit state=restarted


#  - name: Stop HAPROXY and Enable it on the every boot
#    service: name=haproxy state=stopped enabled=no

  when: ansible_system == "Linux"
